name: CIBuild
# jscpd:ignore-start
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - dev
    # Sequence of patterns matched against refs/tags
    tags:        
      - '*'
  pull_request:
    types: [ assigned, opened, synchronize, reopened, labeled ]
jobs:
  ci_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        # cpu: [amd64]
        cpu: [amd64, arm_eabi, arm_eabihf, aarch64]
        exclude:
          - os: windows-latest
            cpu: arm_eabi
          - os: windows-latest
            cpu: arm_eabihf
          - os: windows-latest
            cpu: aarch64
          - os: macos-latest
            cpu: arm_eabi
          - os: macos-latest
            cpu: arm_eabihf
          - os: macos-latest
            cpu: aarch64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Get the tag version
        id: get_version
        if: startsWith(github.ref, 'refs/tags/')
        run: echo BUILD_VERSION="$(echo "${GITHUB_REF}" | cut -d / -f 3)" >> "$GITHUB_ENV"
        shell: bash
      - name: Get the commit version
        if: startsWith(github.ref, 'refs/tags/') != true
        run: echo BUILD_VERSION="${GITHUB_SHA}" >> "$GITHUB_ENV"
        shell: bash
      - uses: bazelbuild/setup-bazelisk@v2
      - name: Build
        run: sh ./scripts/ci_build.sh ${{ matrix.cpu }}
        shell: bash
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          files: snova_asio_**.tar.bz2
# jscpd:ignore-end
  