name: "example-cron-action"
on:
  schedule:
    - cron:  '*/15 * * * *'    # At every 15th minute

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.3.0
        id: author-date
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const commit_details = await github.git.getCommit({owner: context.repo.owner, repo: context.repo.repo, commit_sha: context.sha});
            return commit_details.data.author.date
      - run: echo $COMMITTED_AT | cut -d T -f 1 | sed 's/-//g'
        env:
          COMMITTED_AT: ${{ steps.author-date.outputs.result }}